# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68561b2f26f14af81e3769715f2e79f0209d874a041f282ec568fd69d406aa1ffc89ae30dde1fef4f45bdfbb97c020b67eaf33b4fbef753e9cc05b2ead16e8ad

test:
  secret_key_base: c67f8616b619f678b6b90d2227017d8f1b8684250a020d065c857b05cebb63bd9c23c9c8a6012dc5d0da5100d07614b9f4e137f0781edff3b61ab126145bc3f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
